# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: deglier amorim - Desenvolvedor Web
email: degliersa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog para simplicar a vida do programador Web :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://deglier.github.io" # the base hostname & protocol for your site
face_username: deglier.amorim
twitter_username: degliersa
github_username:  deglier
analytics_id: UA-70396889-1
facebook_id: 1520500464940705
# Build settings
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM

links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Séries
    url: /series

exclude: ['package.json', 'src', 'node_modules', 'dependencias.txt', 'gulpfile.js']
